workflows:
  ios-workflow:
    name: WakeMap iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # Configuración de la aplicación
        APP_ID: "com.example.tfg_definitivo2"
        BUNDLE_ID: "com.example.tfg_definitivo2"
        APP_NAME: "WakeMap"
        
    scripts:
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
          
      - name: Flutter analyze
        script: |
          flutter packages get
          flutter analyze --no-fatal-infos || echo "Analysis completed with warnings"
          
      - name: Flutter unit tests
        script: |
          flutter test
          
      - name: Build iOS app (no signing)
        script: |
          flutter build ios --release --no-codesign \
            --build-name=1.0.0 \
            --build-number=1
            
    artifacts:
      - build/ios/Release-iphoneos/*.app
      - flutter_drive.log
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      
    publishing:
      # Configuración para notificaciones
      email:
        recipients:
          - ernesto.contreras@example.com
        notify:
          success: true
          failure: true
