name: tfg_definitivo2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.2.0
  google_places_flutter: ^2.1.0
  google_maps_webservice: 0.0.20-nullsafety.5
  location: ^8.0.0
  permission_handler: ^12.0.0+1
  sqflite: ^2.0.0
  path: ^1.8.0
  http: ^0.13.6
  geolocator: ^14.0.0
  flutter_local_notifications: ^18.0.1
  audioplayers: ^6.4.0
  flutter_launcher_icons: ^0.14.3
  sqflite_common_ffi: ^2.0.0+3
  speech_to_text: ^7.2.0
  logger: ^2.0.2+1
  
  # Optimizaciones de rendimiento
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  
  # Internacionalización
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter_icons:
  android: true
  image_path: "assets/images/icono.png"

flutter:
  uses-material-design: true
  assets:
    - assets/audios/alarmaClasica.mp3
    - assets/audios/despertarSuave.mp3
    - assets/audios/alarmaUrgente.mp3
    - assets/audios/alarmaNaturaleza.mp3
    - assets/audios/alarmaTropical.mp3
    - assets/radius_marker.png

  fonts:
    - family: MiFuente1
      fonts:
        - asset: assets/fonts/DS-DIGIB.TTF
    - family: MiFuente2
      fonts:
        - asset: assets/fonts/Ripe Mango Demo.ttf
    - family: MiFuente3Bold
      fonts:
        - asset: assets/fonts/Champagne & Limousines Bold.ttf
    - family: MiFuente3
      fonts:
        - asset: assets/fonts/Champagne & Limousines.ttf